name: cotf-py37
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.7
  - pip
  - cudatoolkit=10.2
  - pytorch==1.8.1
  - torchvision==0.9.1
  - torchaudio==0.8.1
  - pip:
      - opencv-python
      - pyyaml
      - -r third_party/CoTF/requirements.txt